apiVersion: apps/v1
kind: Deployment
metadata:
  name: yw3-iv-calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yw3-iv-calculator
  template:
    metadata:
      labels:
        app: yw3-iv-calculator
    spec:
      containers:
        - name: web
          image: ghcr.io/alexandergg-0520/yw3-iv-calculator:d7ba5ded52ba3012964ffbeff19018a89f4f006b
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          securityContext:
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: yw3-iv-calculator
spec:
  selector:
    app: yw3-iv-calculator
  ports:
    - port: 80
      targetPort: 80
