apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yw3-iv-calculator
  namespace: argocd
  labels:
    app.kubernetes.io/name: yw3-iv-calculator
    app.kubernetes.io/part-of: yw3-iv-calculator
spec:
  project: default

  source:
    repoURL: "https://github.com/AlexanderGG-0520/yw3-iv-calculator.git"
    targetRevision: main
    path: infra/kubernetes
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: yw3-iv

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 5
